### ISSUE TITLE
renaming of radio_simus.signal_processing "run" to  "standard_signal_processing"

### ISSUE THREAD

**Issue by mjtueros** [azilles/radio-simus#2]
or something like that. We should have a "default" signal simulation chain, and why not put it here? (we can later discuss what would be the propper details of the standard chain).
(maybe with parameters for enabling/disabling noise (and how much?) and filtering and digitization

**Comment by azilles** [comment]
This is a good idea

**Comment by azilles** [comment]
* run() now renamed to standard_processing()
* not enabled to pick options since then it is not standard anymore :)
